"""initial tables

Revision ID: 271cad486c4c
Revises: 
Create Date: 2026-05-07 00:09:00.801756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '271cad486c4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delay_codes',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vehicle_type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('nodes', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subway_delays',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Text(), nullable=True),
    sa.Column('day', sa.Text(), nullable=True),
    sa.Column('station', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('min_delay', sa.Integer(), nullable=True),
    sa.Column('min_gap', sa.Integer(), nullable=True),
    sa.Column('bound', sa.Text(), nullable=True),
    sa.Column('line', sa.Text(), nullable=True),
    sa.Column('vehicle', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['delay_codes.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subway_delays_date', 'subway_delays', ['date'], unique=False)
    op.create_index('ix_subway_delays_line', 'subway_delays', ['line'], unique=False)
    op.create_index('ix_subway_delays_station', 'subway_delays', ['station'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subway_delays_station', table_name='subway_delays')
    op.drop_index('ix_subway_delays_line', table_name='subway_delays')
    op.drop_index('ix_subway_delays_date', table_name='subway_delays')
    op.drop_table('subway_delays')
    op.drop_table('workflows')
    op.drop_table('delay_codes')
    # ### end Alembic commands ###
